### ISSUE TITLE
Chinese Translation Issue

### ISSUE THREAD

**Issue by Chuanhsing** [PoESkillTree/PoESkillTree#444]
with chinese translation SkillTree.txt strange lines. http://imgur.com/6UVLSOH

can't translate Opts.txt into chinese, got crash.

[Opts_tw.txt](https://github.com/EmmittJ/PoESkillTree/files/813742/Opts_tw.txt)
[SkillTree_tw.txt](https://github.com/EmmittJ/PoESkillTree/files/813743/SkillTree_tw.txt)

**Comment by brather1ng** [comment]
The functionality is based on a lot of hardcoded english strings. We could probably do the core stuff with localization, so most would also work with other languages. But

1. someone else would have to translate these hardcoded strings to their equivalents in other languages
2. other things that heavily rely on strings are completely out of the question, e.g. computation and the tree generator. So the resulting translated program might be heavily cut in functionality and will probably not be supported outside of opening strings up for translation that are reported by others.

**Comment by Chuanhsing** [comment]
1. Regex(@"Can Allocate Passives from the .* starting point") for SkillTree.txt
    How about make this string into Message.pot?

2. the "name" (Marauder, Ranger) in Opts.txt must keep english
    We can use nodes' spc to know which it belongs
    SkillTree.txt nodes: id 58833, dn: Seven, spc: 0
        Opts.txt ascClasses index 0: Scion
    SkillTree.txt nodes: id 50459, dn: RANGER, spc: 2
        Opts.txt ascClasses index 2: Ranger
    SkillTree.txt nodes: id 54447, dn: WITCH, spc: 3
        Opts.txt ascClasses index 3: Witch

**Comment by brather1ng** [comment]
Yes, getting those hardcoded strings into Message.pot is what I mean.

For the core functionality, that shouldn't be much work. However, there are many things that rely on semantics of hardcoded English or on data we only have access to on English: everything related to calculation, the tree generator, everything crafting related, ...

**Comment by brather1ng** [comment]
I don't think putting anything related to localized data into Messages.pot is a good idea.  UI and data localization should be kept as two different things because people might only want to have one of them localized and the game is localized for different languages than the UI.

Localizing data would also include translating (and maintaining) the computation data. That would mean the amount of supported items and skills would depend on the localization and we would have issues opened that are specific to each language. Because of that, I wouldn't want the data to be localized in this repository. If anyone is willing to translate everything data related and maintain that translation, you are free to do that in a fork and I don't mind guiding you to the correct places in the code once the computation stuff is somewhat wrapped up.
