### ISSUE TITLE
Prefixs +# Energy Sheild for items set wrongly

### ISSUE THREAD

**Issue by Songzhenyu1990** [PoESkillTree/PoESkillTree#495]
+# to Armor is used instead of ES for the equipment build.

**Comment by brather1ng** [comment]
That's weird, seems like all flat defenses got put into the same modifier group in 3.0. Because of that, the program can't distinguish between them and puts them all into one group. But in-game it's still possible to get different types of flat defense on an item, so them being in the same group doesn't make any sense.

I'm not sure how to fix this, could just disable master crafted flat defenses (like I did for percent defenses). But then you still could only craft one type of flat defense on hybrid items.

**Comment by brather1ng** [comment]
Turns out the 3.0 patch did change flat defenses to only one mod per item (hybrid flat defenses were added), so doing the same as for percent defenses does make sense. Could have recognized that earlier ...
